# Employee Sales Performance

1. Write a query that finds the total dollar amount of sales assigned to each sales support agent within the company. Add any extra attributes for that employee that you find are relevant to the analysis.
2. Write a short statement describing your results, and providing a possible interpretation.

In [1]:
%%capture
%load_ext sql
%sql sqlite:///chinook.db

## Finding relevant data

Our main metric will be  total dollar amount of purchases assigned to a sales support agent. That means:
1. will need to query:
  * `invoice` to get total amount purchased
  * `customers` to join data about total amount purchased to employees data
  * `employees` 
2. in the `employees` table we can filter to only include employees with `Sales Support Agent` title.

To see what other attributes might influence sales performance let's explore the `employees` table first.

In [2]:
%%sql

SELECT name FROM PRAGMA_TABLE_INFO('employee');

 * sqlite:///chinook.db
Done.

[('employee_id',),
 ('last_name',),
 ('first_name',),
 ('title',),
 ('reports_to',),
 ('birthdate',),
 ('hire_date',),
 ('address',),
 ('city',),
 ('state',),
 ('country',),
 ('postal_code',),
 ('phone',),
 ('fax',),
 ('email',)]

### Place of living

One thing that could influence sales performance is the country (some countries have more people than others and thus more purchases would be expected), but it turns out all agents so far are from Canada.

In [7]:
%%sql

SELECT DISTINCT country 
FROM employee
WHERE title = 'Sales Support Agent'
;

 * sqlite:///chinook.db
Done.

[('Canada',)]

The same goes for city

In [8]:
%%sql

SELECT DISTINCT city 
FROM employee
WHERE title = 'Sales Support Agent'
;

 * sqlite:///chinook.db
Done.

[('Calgary',)]

### Time working

Another obvious reason a sales manager would have more sales is that he was working for a longer period of time. We could check it by exploring the `hire_date` column.

In [9]:
%%sql
SELECT 
	first_name || ' ' || last_name AS name,
	hire_date 
FROM employee e 
WHERE title = 'Sales Support Agent'
;

 * sqlite:///chinook.db
Done.

[('Jane Peacock', '2017-04-01 00:00:00'),
 ('Margaret Park', '2017-05-03 00:00:00'),
 ('Steve Johnson', '2017-10-17 00:00:00')]

The agents indeed were not hired simultaniously, so we need to take it into account and probably group data by month.

### Other relevant data

There might be some other reasons why any particular sales agent doing better or worse:
* he might be just lucky to first serve a very large client (something like Apple)
* there might be some promotion going on that results in more sales, while one of the Agents is on the vacation

And there might be others. So there needs to be an understanding that these metrics might be not very indicative especially given there is so little data - only three sales agents and we don't have any data at all to check against those extra scenarios.

### Chosen source data

So we end up with 3 time series (say per day or month) for each sales agent measuring how much dollars in total they've made.

In [10]:
%%sql

SELECT 
	e.first_name || ' ' || e.last_name AS name,
	i.invoice_date,
	sum(i.total) AS total
FROM invoice i 
INNER JOIN customer c
	ON c.customer_id = i.customer_id 
INNER JOIN employee e
	ON e.employee_id = c.support_rep_id 
GROUP BY 
	1,
	2 
;

 * sqlite:///chinook.db
Done.

[('Jane Peacock', '2017-01-03 00:00:00', 25.740000000000002),
 ('Jane Peacock', '2017-01-06 00:00:00', 7.92),
 ('Jane Peacock', '2017-01-13 00:00:00', 9.9),
 ('Jane Peacock', '2017-01-18 00:00:00', 8.91),
 ('Jane Peacock', '2017-01-20 00:00:00', 10.89),
 ('Jane Peacock', '2017-01-21 00:00:00', 3.96),
 ('Jane Peacock', '2017-01-25 00:00:00', 3.96),
 ('Jane Peacock', '2017-01-26 00:00:00', 8.91),
 ('Jane Peacock', '2017-02-02 00:00:00', 4.95),
 ('Jane Peacock', '2017-02-06 00:00:00', 9.9),
 ('Jane Peacock', '2017-02-09 00:00:00', 9.9),
 ('Jane Peacock', '2017-02-17 00:00:00', 8.91),
 ('Jane Peacock', '2017-02-18 00:00:00', 10.89),
 ('Jane Peacock', '2017-02-21 00:00:00', 36.63),
 ('Jane Peacock', '2017-02-23 00:00:00', 0.99),
 ('Jane Peacock', '2017-03-05 00:00:00', 9.9),
 ('Jane Peacock', '2017-03-13 00:00:00', 9.9),
 ('Jane Peacock', '2017-03-18 00:00:00', 8.91),
 ('Jane Peacock', '2017-03-28 00:00:00', 3.96),
 ('Jane Peacock', '2017-04-02 00:00:00', 6.93),
 ('Jane Peacock', '2017-04-03 00:00:00', 7.92),
 ('Jane Peacock', '2017-04-11 00:00:00', 11.879999999999999),
 ('Jane Peacock', '2017-04-12 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2017-04-16 00:00:00', 9.9),
 ('Jane Peacock', '2017-04-22 00:00:00', 0.99),
 ('Jane Peacock', '2017-04-24 00:00:00', 30.69),
 ('Jane Peacock', '2017-04-25 00:00:00', 12.87),
 ('Jane Peacock', '2017-05-17 00:00:00', 16.83),
 ('Jane Peacock', '2017-05-28 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2017-06-13 00:00:00', 6.93),
 ('Jane Peacock', '2017-06-17 00:00:00', 4.95),
 ('Jane Peacock', '2017-06-18 00:00:00', 0.99),
 ('Jane Peacock', '2017-06-20 00:00:00', 7.92),
 ('Jane Peacock', '2017-07-05 00:00:00', 9.9),
 ('Jane Peacock', '2017-07-10 00:00:00', 10.89),
 ('Jane Peacock', '2017-07-17 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2017-07-31 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2017-08-27 00:00:00', 4.95),
 ('Jane Peacock', '2017-08-29 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2017-09-05 00:00:00', 16.83),
 ('Jane Peacock', '2017-09-10 00:00:00', 10.89),
 ('Jane Peacock', '2017-09-19 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2017-09-20 00:00:00', 8.91),
 ('Jane Peacock', '2017-09-29 00:00:00', 9.9),
 ('Jane Peacock', '2017-10-29 00:00:00', 3.96),
 ('Jane Peacock', '2017-10-30 00:00:00', 10.89),
 ('Jane Peacock', '2017-11-06 00:00:00', 7.92),
 ('Jane Peacock', '2017-11-07 00:00:00', 17.82),
 ('Jane Peacock', '2017-11-10 00:00:00', 14.85),
 ('Jane Peacock', '2017-11-18 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2017-11-22 00:00:00', 12.87),
 ('Jane Peacock', '2017-11-28 00:00:00', 4.95),
 ('Jane Peacock', '2017-11-30 00:00:00', 17.82),
 ('Jane Peacock', '2017-12-12 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2017-12-14 00:00:00', 13.86),
 ('Jane Peacock', '2018-01-02 00:00:00', 8.91),
 ('Jane Peacock', '2018-01-13 00:00:00', 7.92),
 ('Jane Peacock', '2018-01-28 00:00:00', 9.9),
 ('Jane Peacock', '2018-01-30 00:00:00', 12.87),
 ('Jane Peacock', '2018-01-31 00:00:00', 14.85),
 ('Jane Peacock', '2018-02-05 00:00:00', 9.9),
 ('Jane Peacock', '2018-02-06 00:00:00', 6.93),
 ('Jane Peacock', '2018-02-07 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2018-02-09 00:00:00', 24.749999999999996),
 ('Jane Peacock', '2018-02-18 00:00:00', 6.93),
 ('Jane Peacock', '2018-03-02 00:00:00', 9.9),
 ('Jane Peacock', '2018-03-05 00:00:00', 10.89),
 ('Jane Peacock', '2018-03-08 00:00:00', 7.92),
 ('Jane Peacock', '2018-03-16 00:00:00', 9.9),
 ('Jane Peacock', '2018-03-31 00:00:00', 11.879999999999999),
 ('Jane Peacock', '2018-04-01 00:00:00', 10.89),
 ('Jane Peacock', '2018-04-25 00:00:00', 8.91),
 ('Jane Peacock', '2018-05-04 00:00:00', 17.82),
 ('Jane Peacock', '2018-05-12 00:00:00', 10.89),
 ('Jane Peacock', '2018-05-16 00:00:00', 9.9),
 ('Jane Peacock', '2018-05-19 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2018-05-27 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2018-06-13 00:00:00', 15.84),
 ('Jane Peacock', '2018-06-14 00:00:00', 9.9),
 ('Jane Peacock', '2018-06-16 00:00:00', 15.84),
 ('Jane Peacock', '2018-06-18 00:00:00', 1.98),
 ('Jane Peacock', '2018-06-23 00:00:00', 4.95),
 ('Jane Peacock', '2018-07-12 00:00:00', 8.91),
 ('Jane Peacock', '2018-07-13 00:00:00', 6.93),
 ('Jane Peacock', '2018-07-14 00:00:00', 1.98),
 ('Jane Peacock', '2018-07-25 00:00:00', 7.92),
 ('Jane Peacock', '2018-07-31 00:00:00', 3.96),
 ('Jane Peacock', '2018-08-03 00:00:00', 6.93),
 ('Jane Peacock', '2018-08-09 00:00:00', 7.92),
 ('Jane Peacock', '2018-08-15 00:00:00', 0.99),
 ('Jane Peacock', '2018-08-18 00:00:00', 6.93),
 ('Jane Peacock', '2018-08-22 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2018-08-26 00:00:00', 0.99),
 ('Jane Peacock', '2018-08-27 00:00:00', 10.89),
 ('Jane Peacock', '2018-09-02 00:00:00', 16.83),
 ('Jane Peacock', '2018-09-10 00:00:00', 4.95),
 ('Jane Peacock', '2018-10-25 00:00:00', 9.9),
 ('Jane Peacock', '2018-12-02 00:00:00', 10.89),
 ('Jane Peacock', '2018-12-03 00:00:00', 0.99),
 ('Jane Peacock', '2018-12-10 00:00:00', 12.87),
 ('Jane Peacock', '2018-12-13 00:00:00', 8.91),
 ('Jane Peacock', '2018-12-14 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2019-01-06 00:00:00', 10.89),
 ('Jane Peacock', '2019-01-21 00:00:00', 9.9),
 ('Jane Peacock', '2019-01-24 00:00:00', 4.95),
 ('Jane Peacock', '2019-01-29 00:00:00', 9.9),
 ('Jane Peacock', '2019-02-19 00:00:00', 7.92),
 ('Jane Peacock', '2019-02-22 00:00:00', 16.83),
 ('Jane Peacock', '2019-03-04 00:00:00', 18.810000000000002),
 ('Jane Peacock', '2019-03-15 00:00:00', 9.9),
 ('Jane Peacock', '2019-03-21 00:00:00', 20.79),
 ('Jane Peacock', '2019-04-03 00:00:00', 4.95),
 ('Jane Peacock', '2019-04-13 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2019-04-15 00:00:00', 16.83),
 ('Jane Peacock', '2019-04-17 00:00:00', 3.96),
 ('Jane Peacock', '2019-04-21 00:00:00', 3.96),
 ('Jane Peacock', '2019-05-04 00:00:00', 6.93),
 ('Jane Peacock', '2019-05-12 00:00:00', 15.84),
 ('Jane Peacock', '2019-05-15 00:00:00', 3.96),
 ('Jane Peacock', '2019-05-24 00:00:00', 22.77),
 ('Jane Peacock', '2019-06-01 00:00:00', 13.86),
 ('Jane Peacock', '2019-06-03 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2019-07-11 00:00:00', 6.93),
 ('Jane Peacock', '2019-07-20 00:00:00', 3.96),
 ('Jane Peacock', '2019-07-28 00:00:00', 9.9),
 ('Jane Peacock', '2019-07-29 00:00:00', 8.91),
 ('Jane Peacock', '2019-08-06 00:00:00', 9.9),
 ('Jane Peacock', '2019-08-28 00:00:00', 7.92),
 ('Jane Peacock', '2019-09-01 00:00:00', 9.9),
 ('Jane Peacock', '2019-09-02 00:00:00', 9.9),
 ('Jane Peacock', '2019-09-07 00:00:00', 6.93),
 ('Jane Peacock', '2019-09-14 00:00:00', 4.95),
 ('Jane Peacock', '2019-09-17 00:00:00', 3.96),
 ('Jane Peacock', '2019-09-24 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2019-09-28 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2019-10-08 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2019-10-26 00:00:00', 6.93),
 ('Jane Peacock', '2019-11-05 00:00:00', 3.96),
 ('Jane Peacock', '2019-11-08 00:00:00', 8.91),
 ('Jane Peacock', '2019-11-23 00:00:00', 10.89),
 ('Jane Peacock', '2019-11-27 00:00:00', 9.9),
 ('Jane Peacock', '2019-12-13 00:00:00', 0.99),
 ('Jane Peacock', '2019-12-21 00:00:00', 14.85),
 ('Jane Peacock', '2019-12-25 00:00:00', 14.85),
 ('Jane Peacock', '2019-12-26 00:00:00', 0.99),
 ('Jane Peacock', '2019-12-31 00:00:00', 3.96),
 ('Jane Peacock', '2020-01-19 00:00:00', 3.96),
 ('Jane Peacock', '2020-02-02 00:00:00', 3.96),
 ('Jane Peacock', '2020-02-21 00:00:00', 16.83),
 ('Jane Peacock', '2020-02-22 00:00:00', 9.9),
 ('Jane Peacock', '2020-02-25 00:00:00', 3.96),
 ('Jane Peacock', '2020-02-29 00:00:00', 4.95),
 ('Jane Peacock', '2020-03-05 00:00:00', 18.810000000000002),
 ('Jane Peacock', '2020-03-14 00:00:00', 11.879999999999999),
 ('Jane Peacock', '2020-04-10 00:00:00', 3.96),
 ('Jane Peacock', '2020-04-14 00:00:00', 16.83),
 ('Jane Peacock', '2020-04-22 00:00:00', 8.91),
 ('Jane Peacock', '2020-05-01 00:00:00', 6.93),
 ('Jane Peacock', '2020-05-02 00:00:00', 8.91),
 ('Jane Peacock', '2020-05-16 00:00:00', 8.91),
 ('Jane Peacock', '2020-06-02 00:00:00', 9.9),
 ('Jane Peacock', '2020-06-12 00:00:00', 13.86),
 ('Jane Peacock', '2020-06-22 00:00:00', 11.879999999999999),
 ('Jane Peacock', '2020-07-06 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2020-07-07 00:00:00', 7.92),
 ('Jane Peacock', '2020-07-12 00:00:00', 11.88),
 ('Jane Peacock', '2020-07-15 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2020-07-24 00:00:00', 8.91),
 ('Jane Peacock', '2020-07-26 00:00:00', 7.92),
 ('Jane Peacock', '2020-08-02 00:00:00', 10.89),
 ('Jane Peacock', '2020-08-12 00:00:00', 9.9),
 ('Jane Peacock', '2020-08-19 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2020-08-27 00:00:00', 8.91),
 ('Jane Peacock', '2020-09-20 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2020-09-23 00:00:00', 9.9),
 ('Jane Peacock', '2020-09-27 00:00:00', 12.870000000000001),
 ('Jane Peacock', '2020-10-07 00:00:00', 2.9699999999999998),
 ('Jane Peacock', '2020-10-19 00:00:00', 9.899999999999999),
 ('Jane Peacock', '2020-10-25 00:00:00', 9.9),
 ('Jane Peacock', '2020-10-31 00:00:00', 0.99),
 ('Jane Peacock', '2020-11-07 00:00:00', 1.98),
 ('Jane Peacock', '2020-11-23 00:00:00', 10.89),
 ('Jane Peacock', '2020-11-27 00:00:00', 5.9399999999999995),
 ('Jane Peacock', '2020-12-06 00:00:00', 7.92),
 ('Jane Peacock', '2020-12-08 00:00:00', 15.84),
 ('Jane Peacock', '2020-12-12 00:00:00', 17.82),
 ('Jane Peacock', '2020-12-18 00:00:00', 11.879999999999999),
 ('Jane Peacock', '2020-12-19 00:00:00', 4.95),
 ('Jane Peacock', '2020-12-27 00:00:00', 13.86),
 ('Jane Peacock', '2020-12-30 00:00:00', 12.87),
 ('Margaret Park', '2017-01-05 00:00:00', 1.98),
 ('Margaret Park', '2017-01-07 00:00:00', 16.83),
 ('Margaret Park', '2017-01-12 00:00:00', 10.89),
 ('Margaret Park', '2017-01-22 00:00:00', 0.99),
 ('Margaret Park', '2017-01-28 00:00:00', 10.89),
 ('Margaret Park', '2017-02-06 00:00:00', 6.93),
 ('Margaret Park', '2017-02-07 00:00:00', 8.91),
 ('Margaret Park', '2017-02-08 00:00:00', 1.98),
 ('Margaret Park', '2017-02-10 00:00:00', 11.879999999999999),
 ('Margaret Park', '2017-02-11 00:00:00', 7.92),
 ('Margaret Park', '2017-02-15 00:00:00', 9.9),
 ('Margaret Park', '2017-02-25 00:00:00', 4.95),
 ('Margaret Park', '2017-03-05 00:00:00', 6.93),
 ('Margaret Park', '2017-03-12 00:00:00', 7.92),
 ('Margaret Park', '2017-03-19 00:00:00', 6.93),
 ('Margaret Park', '2017-03-24 00:00:00', 10.89),
 ('Margaret Park', '2017-03-30 00:00:00', 4.95),
 ('Margaret Park', '2017-04-13 00:00:00', 17.82),
 ('Margaret Park', '2017-04-22 00:00:00', 16.83),
 ('Margaret Park', '2017-04-23 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2017-04-25 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2017-04-29 00:00:00', 6.93),
 ('Margaret Park', '2017-05-01 00:00:00', 10.89),
 ('Margaret Park', '2017-05-18 00:00:00', 16.83),
 ('Margaret Park', '2017-05-24 00:00:00', 3.96),
 ('Margaret Park', '2017-05-26 00:00:00', 12.87),
 ('Margaret Park', '2017-05-29 00:00:00', 8.91),
 ('Margaret Park', '2017-06-08 00:00:00', 0.99),
 ('Margaret Park', '2017-06-12 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2017-06-15 00:00:00', 3.96),
 ('Margaret Park', '2017-06-28 00:00:00', 10.89),
 ('Margaret Park', '2017-07-02 00:00:00', 19.8),
 ('Margaret Park', '2017-07-22 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2017-07-28 00:00:00', 17.82),
 ('Margaret Park', '2017-07-31 00:00:00', 3.96),
 ('Margaret Park', '2017-08-02 00:00:00', 9.9),
 ('Margaret Park', '2017-08-03 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2017-08-06 00:00:00', 1.98),
 ('Margaret Park', '2017-08-21 00:00:00', 10.89),
 ('Margaret Park', '2017-08-29 00:00:00', 10.89),
 ('Margaret Park', '2017-08-30 00:00:00', 4.95),
 ('Margaret Park', '2017-09-01 00:00:00', 9.9),
 ('Margaret Park', '2017-09-12 00:00:00', 1.98),
 ('Margaret Park', '2017-09-21 00:00:00', 4.95),
 ('Margaret Park', '2017-09-25 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2017-10-07 00:00:00', 3.96),
 ('Margaret Park', '2017-10-08 00:00:00', 10.89),
 ('Margaret Park', '2017-10-19 00:00:00', 3.96),
 ('Margaret Park', '2017-10-22 00:00:00', 9.9),
 ('Margaret Park', '2017-10-29 00:00:00', 1.98),
 ('Margaret Park', '2017-11-03 00:00:00', 4.95),
 ('Margaret Park', '2017-12-01 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2017-12-06 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2017-12-17 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-01-03 00:00:00', 10.89),
 ('Margaret Park', '2018-01-08 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2018-01-20 00:00:00', 3.96),
 ('Margaret Park', '2018-01-31 00:00:00', 28.71),
 ('Margaret Park', '2018-02-02 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-02-20 00:00:00', 10.89),
 ('Margaret Park', '2018-02-21 00:00:00', 3.96),
 ('Margaret Park', '2018-02-27 00:00:00', 0.99),
 ('Margaret Park', '2018-03-02 00:00:00', 10.89),
 ('Margaret Park', '2018-03-05 00:00:00', 10.89),
 ('Margaret Park', '2018-03-08 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-03-11 00:00:00', 11.879999999999999),
 ('Margaret Park', '2018-03-17 00:00:00', 10.89),
 ('Margaret Park', '2018-03-20 00:00:00', 9.9),
 ('Margaret Park', '2018-03-22 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2018-03-25 00:00:00', 3.96),
 ('Margaret Park', '2018-04-04 00:00:00', 1.98),
 ('Margaret Park', '2018-04-14 00:00:00', 4.95),
 ('Margaret Park', '2018-04-17 00:00:00', 9.9),
 ('Margaret Park', '2018-04-19 00:00:00', 8.91),
 ('Margaret Park', '2018-04-21 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-04-25 00:00:00', 7.92),
 ('Margaret Park', '2018-05-06 00:00:00', 9.9),
 ('Margaret Park', '2018-06-06 00:00:00', 6.93),
 ('Margaret Park', '2018-06-08 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-06-17 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-06-30 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-07-12 00:00:00', 10.89),
 ('Margaret Park', '2018-07-20 00:00:00', 10.89),
 ('Margaret Park', '2018-07-29 00:00:00', 11.879999999999999),
 ('Margaret Park', '2018-07-31 00:00:00', 4.95),
 ('Margaret Park', '2018-08-01 00:00:00', 10.89),
 ('Margaret Park', '2018-08-04 00:00:00', 7.92),
 ('Margaret Park', '2018-08-06 00:00:00', 8.91),
 ('Margaret Park', '2018-08-22 00:00:00', 1.98),
 ('Margaret Park', '2018-08-23 00:00:00', 10.89),
 ('Margaret Park', '2018-08-30 00:00:00', 8.91),
 ('Margaret Park', '2018-09-04 00:00:00', 4.95),
 ('Margaret Park', '2018-09-07 00:00:00', 18.81),
 ('Margaret Park', '2018-09-23 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-10-11 00:00:00', 16.83),
 ('Margaret Park', '2018-10-16 00:00:00', 10.89),
 ('Margaret Park', '2018-10-25 00:00:00', 1.98),
 ('Margaret Park', '2018-11-04 00:00:00', 1.98),
 ('Margaret Park', '2018-11-06 00:00:00', 6.93),
 ('Margaret Park', '2018-11-19 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-11-21 00:00:00', 9.9),
 ('Margaret Park', '2018-12-11 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2018-12-15 00:00:00', 7.92),
 ('Margaret Park', '2018-12-18 00:00:00', 3.96),
 ('Margaret Park', '2018-12-23 00:00:00', 6.93),
 ('Margaret Park', '2018-12-26 00:00:00', 14.85),
 ('Margaret Park', '2019-01-01 00:00:00', 10.89),
 ('Margaret Park', '2019-01-05 00:00:00', 9.9),
 ('Margaret Park', '2019-01-16 00:00:00', 8.91),
 ('Margaret Park', '2019-01-18 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2019-01-30 00:00:00', 4.95),
 ('Margaret Park', '2019-02-14 00:00:00', 11.879999999999999),
 ('Margaret Park', '2019-03-03 00:00:00', 7.92),
 ('Margaret Park', '2019-03-05 00:00:00', 8.91),
 ('Margaret Park', '2019-03-08 00:00:00', 3.96),
 ('Margaret Park', '2019-03-09 00:00:00', 0.99),
 ('Margaret Park', '2019-03-13 00:00:00', 12.87),
 ('Margaret Park', '2019-04-09 00:00:00', 11.879999999999999),
 ('Margaret Park', '2019-04-17 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2019-04-18 00:00:00', 8.91),
 ('Margaret Park', '2019-04-23 00:00:00', 0.99),
 ('Margaret Park', '2019-05-02 00:00:00', 4.95),
 ('Margaret Park', '2019-05-04 00:00:00', 6.93),
 ('Margaret Park', '2019-05-08 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2019-05-18 00:00:00', 1.98),
 ('Margaret Park', '2019-05-26 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2019-05-27 00:00:00', 8.91),
 ('Margaret Park', '2019-05-29 00:00:00', 7.92),
 ('Margaret Park', '2019-05-30 00:00:00', 1.98),
 ('Margaret Park', '2019-06-01 00:00:00', 3.96),
 ('Margaret Park', '2019-06-05 00:00:00', 8.91),
 ('Margaret Park', '2019-06-06 00:00:00', 3.96),
 ('Margaret Park', '2019-06-14 00:00:00', 9.9),
 ('Margaret Park', '2019-06-21 00:00:00', 12.87),
 ('Margaret Park', '2019-07-03 00:00:00', 9.9),
 ('Margaret Park', '2019-07-12 00:00:00', 4.95),
 ('Margaret Park', '2019-07-16 00:00:00', 9.9),
 ('Margaret Park', '2019-07-18 00:00:00', 16.83),
 ('Margaret Park', '2019-07-19 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2019-08-15 00:00:00', 1.98),
 ('Margaret Park', '2019-08-20 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2019-08-27 00:00:00', 1.98),
 ('Margaret Park', '2019-08-31 00:00:00', 0.99),
 ('Margaret Park', '2019-09-05 00:00:00', 9.9),
 ('Margaret Park', '2019-09-09 00:00:00', 1.98),
 ('Margaret Park', '2019-09-14 00:00:00', 14.85),
 ('Margaret Park', '2019-09-17 00:00:00', 10.89),
 ('Margaret Park', '2019-09-20 00:00:00', 1.98),
 ('Margaret Park', '2019-09-21 00:00:00', 9.9),
 ('Margaret Park', '2019-09-23 00:00:00', 1.98),
 ('Margaret Park', '2019-09-27 00:00:00', 9.9),
 ('Margaret Park', '2019-10-04 00:00:00', 10.89),
 ('Margaret Park', '2019-11-07 00:00:00', 7.92),
 ('Margaret Park', '2019-11-11 00:00:00', 3.96),
 ('Margaret Park', '2019-11-19 00:00:00', 8.91),
 ('Margaret Park', '2019-11-27 00:00:00', 16.83),
 ('Margaret Park', '2019-12-04 00:00:00', 6.93),
 ('Margaret Park', '2019-12-24 00:00:00', 9.9),
 ('Margaret Park', '2019-12-28 00:00:00', 10.89),
 ('Margaret Park', '2019-12-30 00:00:00', 11.879999999999999),
 ('Margaret Park', '2020-01-20 00:00:00', 9.9),
 ('Margaret Park', '2020-01-29 00:00:00', 1.98),
 ('Margaret Park', '2020-01-30 00:00:00', 0.99),
 ('Margaret Park', '2020-02-04 00:00:00', 6.93),
 ('Margaret Park', '2020-02-15 00:00:00', 6.93),
 ('Margaret Park', '2020-02-26 00:00:00', 7.92),
 ('Margaret Park', '2020-03-11 00:00:00', 9.9),
 ('Margaret Park', '2020-03-31 00:00:00', 9.9),
 ('Margaret Park', '2020-04-01 00:00:00', 7.92),
 ('Margaret Park', '2020-04-02 00:00:00', 3.96),
 ('Margaret Park', '2020-04-11 00:00:00', 9.9),
 ('Margaret Park', '2020-05-15 00:00:00', 2.9699999999999998),
 ('Margaret Park', '2020-05-16 00:00:00', 1.98),
 ('Margaret Park', '2020-05-22 00:00:00', 8.91),
 ('Margaret Park', '2020-05-26 00:00:00', 9.9),
 ('Margaret Park', '2020-05-27 00:00:00', 11.879999999999999),
 ('Margaret Park', '2020-06-08 00:00:00', 19.8),
 ('Margaret Park', '2020-06-23 00:00:00', 13.86),
 ('Margaret Park', '2020-06-25 00:00:00', 5.9399999999999995),
 ('Margaret Park', '2020-07-05 00:00:00', 0.99),
 ('Margaret Park', '2020-07-18 00:00:00', 10.89),
 ('Margaret Park', '2020-07-30 00:00:00', 6.93),
 ('Margaret Park', '2020-08-18 00:00:00', 10.89),
 ('Margaret Park', '2020-09-04 00:00:00', 1.98),
 ('Margaret Park', '2020-09-11 00:00:00', 14.85),
 ('Margaret Park', '2020-09-12 00:00:00', 6.93),
 ('Margaret Park', '2020-09-17 00:00:00', 8.91),
 ('Margaret Park', '2020-09-19 00:00:00', 1.98),
 ('Margaret Park', '2020-10-01 00:00:00', 6.93),
 ('Margaret Park', '2020-10-13 00:00:00', 4.95),
 ('Margaret Park', '2020-10-16 00:00:00', 10.89),
 ('Margaret Park', '2020-10-17 00:00:00', 10.89),
 ('Margaret Park', '2020-10-26 00:00:00', 13.86),
 ('Margaret Park', '2020-10-30 00:00:00', 28.71),
 ('Margaret Park', '2020-10-31 00:00:00', 8.91),
 ('Margaret Park', '2020-11-01 00:00:00', 10.89),
 ('Margaret Park', '2020-11-12 00:00:00', 0.99),
 ('Margaret Park', '2020-11-20 00:00:00', 6.93),
 ('Margaret Park', '2020-11-27 00:00:00', 7.92),
 ('Margaret Park', '2020-11-28 00:00:00', 6.93),
 ('Margaret Park', '2020-12-04 00:00:00', 4.95),

Ok, this turned out to be not very human readable and we could do visualization of these time series (or grouping say by month) to see how well is every sales agent is doing comparatively to each other and what are the tendancies, but want we want now is simplier - we just need to see how much overall every agent has sold. We can skip the 2017 year just to make comparison fair for those hired later.

In [12]:
%%sql
SELECT 
	e.first_name || ' ' || e.last_name AS name,
	sum(i.total) AS total
FROM invoice i 
INNER JOIN customer c
	ON c.customer_id = i.customer_id 
INNER JOIN employee e
	ON e.employee_id = c.support_rep_id 
WHERE i.invoice_date >= '2018-01-01 00:00:00'
GROUP BY 
	1
ORDER BY 2 DESC
;

 * sqlite:///chinook.db
Done.

[('Jane Peacock', 1198.8900000000012),
 ('Margaret Park', 1167.2100000000007),
 ('Steve Johnson', 1141.4700000000007)]

## Conclusion

We can see that agents are very close in their results with Jane Peacock leading